package domain;

public enum TipoEfecto {
    QUEMAR,
    PARALIZAR,
    DORMIR,
    ENVENENAR,
    CONGELAR,
    DRENAR,
    BAJAR_ATAQUE,
    BAJAR_DEFENSA,
    BAJAR_ATAQUE_ESPECIAL,
    BAJAR_DEFENSA_ESPECIAL,
    BAJAR_VELOCIDAD,
    SUBIR_ATAQUE,
    SUBIR_DEFENSA,
    SUBIR_ATAQUE_ESPECIAL,
    SUBIR_DEFENSA_ESPECIAL,
    SUBIR_VELOCIDAD
} 